### ISSUE TITLE
Update metadata for labs according to modifications in G4.3

### ISSUE THREAD

**Issue by Wissam-Halimi** [go-lab/smart-device#28]
Add parameter `type` to the values. You can find the allowed data types [here](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types).
E.g.:
```
"values": [{
   "name": "left",
   "unit": "radian",
   "type":  "float",
   "rangeMinimum": 0.00,
   "rangeMaximum": 3.14,
   "rangeStep": 0.10,
   "updateFrequency": 10,
   "lastMeasured": "2014-06-23T19:25:43.511Z"
}]
```

@GermanCF maybe you want to update your metadata as well.

**Comment by GermanCF** [comment]
Ok, I’ll review all metadata of the robotic arm and I’ll update/change them if needed.
For example, in my metadata, currently the date and time are updated every second on real time dinamically.

Best,
Germán

**Comment by Wissam-Halimi** [comment]
@GermanCF great!!!!
PLEASE note that the values of parameters in your metadata don't have to match the example I provided in my previous comment.  So your system of course can remain the same, just add the field as mentioned before.

**Comment by GermanCF** [comment]
Ok, I'll only add your field.
Thank you :)
Germán

**Comment by Wissam-Halimi** [comment]
perfect! and plz don't forget to create a separate branch for that

**Comment by GermanCF** [comment]
Sorry, Do you prefer that I update my Raspberry branch or that I create a new branch only with the metadata changes?
